# -*- coding: utf-8 -*-
"""damin_tugas3_wiki4he.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17BPxZn3ImD3f9Njg30KSjSqt5M5gmrGU

## Adding Library and Uploading dataset
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/00334/wiki4HE.csv', sep=';', na_values='?')
wiki4 = data.copy()

wiki4.shape

wiki4.head()

"""dari wiki4 diatas kebanyakan missing values terjadi di other position dan other status

### Menjumlahkan missing values dalam dataset
"""

wiki4.isnull().sum()

"""# Mengubah missing values menjadi probabilitas nol"""

wiki4.fillna(0)

"""Using PCA for Dimensionality Reduction"""

column_item1 = ['AGE', 'GENDER', 'DOMAIN', 'PhD', 'YEARSEXP', 'UNIVERSITY', 'UOC_POSITION', 'OTHER_POSITION',
                 'OTHERSTATUS', 'USERWIKI', 'ENJ1', 'ENJ2']
wiki_item = wiki4.copy()
wiki_item = wiki_item[column_item1]

wiki_item['DOMAIN'].fillna(0, inplace=True)
wiki_item['UOC_POSITION'].fillna(0, inplace=True)
wiki_item['OTHER_POSITION'].fillna(0, inplace=True)
wiki_item['OTHERSTATUS'].fillna(0, inplace=True)
wiki_item['USERWIKI'].fillna(0, inplace=True)
wiki_item['PhD'].fillna(0, inplace=True)
wiki_item['YEARSEXP'].fillna(0, inplace=True)

wiki_item.reset_index(drop=True, inplace=True) # menghapus ulang data yang tidak terpakai

"""## Sampling data menggunakan Sampling without replacement (SWR)

##### data yang digunakan (Age, Gender, PHD), setiap data yang dipilih dipisahkan dari populasi yang lain
"""

gender = wiki_item['GENDER'].copy().replace({0: 'Male', 1: 'Female'}) # pengkategorian nomer 0 sebagai pria dan 1 sebagai wanita
phd = wiki_item['PhD'].copy().replace({0: 'No', 1: 'Yes'}) # pengkategorian nomer 1 sebagai bukan phd, 2 sebagai phd

isPhd_df = pd.concat([wiki_item['AGE'].copy(), gender, phd], axis=1)
isPhd_df.columns = ['AGE', 'GENDER', 'PhD']
ax = sns.catplot(x='PhD', y='AGE', hue='GENDER', kind="swarm",
                 data=isPhd_df, height=6, aspect=1.4/1);